FROM node:18

# Configurer le répertoire de travail
WORKDIR /app

# Copier les fichiers du projet
COPY package*.json ./
COPY . .

# Installer les dépendances
RUN npm install

# Construire l'application pour la production
RUN npm run build

# Exposer le port de développement
EXPOSE 3000

# Démarrer le serveur de développement
CMD ["npm", "start"]
