controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: POST

address_add:
    path: /api/adresses
    controller: App\Controller\AddressController::add
    methods: POST

address_get_by_user:
    path: /api/adresses/user/{userId}
    controller: App\Controller\AddressController::getByUser
    methods: GET

address_delete:
    path: /api/adresses/{id}
    controller: App\Controller\AddressController::deleteAddress
    methods: DELETE

address_get_all:
    path: /api/adresses
    controller: App\Controller\AddressController::getAddresses
    methods: GET



