controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

register:
    path: /api/register
    controller: App\Controller\AuthController::register
    methods: POST

login:
    path: /api/login
    controller: App\Controller\AuthController::login
    methods: POST

adresses:
    path: /api/adresses
    controller: App\Controller\AddressController::getAdresses
    methods: GET

add_address:
    path: /api/adresses
    controller: App\Controller\AddressController::add
    methods: POST

