FROM php:8.2-fpm

# Installer les dépendances requises
RUN apt-get update && apt-get install -y \
    git unzip libpq-dev libicu-dev zlib1g-dev libzip-dev libxml2-dev \
    && docker-php-ext-install pdo pdo_mysql intl zip opcache

# Installer Composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

# Installer Symfony CLI
RUN curl -sS https://get.symfony.com/cli/installer | bash && \
    mv /root/.symfony*/bin/symfony /usr/local/bin/symfony

# Configurer le répertoire de l'application
WORKDIR /app

# Copier les fichiers du projet
COPY . .

# Installer les dépendances
RUN composer install --no-dev --optimize-autoloader
